### ISSUE TITLE
Found 2 Issues.

### ISSUE THREAD

**Issue by aloobhai** [GamehunterKaan/BadUSB-Browser#4]
1)  The inj.txt will open the run cmd and type the irm link. However, it wont press enter (which will execute)
     and the contents remain entered onto the run window and the whole thing stops
2)  If I manually press enter, a powershell window opens but nothing happens. The powershell window opens
     and then closes automatically within 2 seconds. And I've not received any email.

Conclusion- Even though the first issue can be resolved. I'm not sure as to why the second issue is occurring.

Note-
1) I've used mediafire to upload the .exe file and the payload.ps1 . The link to the 'payload.ps1' is added/replaced to 
   the inject.txt file and the link to the .exe file is added/replaced in 'payload.ps1'.
2) I'm using the pico-ducky to run the inj.txt
3) I've allowed the less secure app access (Used it for another duckyscript)

**Comment by GamehunterKaan** [comment]
1. After opening the run window It does `CTRL-SHIFT-ENTER` which executes the command as administrator. Which works perfectly fine for me (I use pico ducky too). You can try changing it to something like `CTRT-SHIFT ENTER` which may work.
2. You shouldn't upload anything to mediafire because mediafire checks for malwares in files. Also to debug powershell you can remove the `-w h` part in command.
